package rmon

const (
	CheckGroupIdFiled        = "check_group"
	PlaceField               = "place"
	EntitiesField            = "entities"
	IntervalField            = "interval"
	TimeoutField             = "check_timeout"
	TelegramField            = "telegram_channel_id"
	SlackField               = "slack_channel_id"
	MMField                  = "mm_channel_id"
	PDField                  = "pd_channel_id"
	PacketSizeField          = "packet_size"
	ResolverField            = "resolver"
	RecordTypeField          = "record_type"
	HttpMethodField          = "http_method"
	IgnoreSslErrorField      = "ignore_ssl_error"
	AcceptedStatusCodesField = "accepted_status_codes"
	BodyField                = "body"
	BodyRequestField         = "body_req"
	HeaderRequestField       = "header_req"
	UrlField                 = "url"
	UserNameField            = "username"
	VhostField               = "vhost"
)
